name: "Go Build Action"
description: "Faz o clone de um repositório e compila um projeto em Go"
inputs:
  commit_hash:
    description: "O hash do commit a usar"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.commit_hash }}
