name: Run 2MS Scan

description: |
  GitHub Action that clones the repositories, builds the 2MS binary, installs dependencies, and runs the scan.

inputs:
  commit_hash:
    description: 'Commit hash to run the scan on'
    required: true

runs:
  using: "docker"
  image: "ubuntu:latest"
  entrypoint: "/bin/bash"
  args: |
    -c "
    # Install system dependencies
    sudo apt-get update
    sudo apt-get install -y python3 python3-pip git npm

    # Clone the 2MS repository using the commit hash from the input
    git clone https://github.com/checkmarx/2ms.git
    cd 2ms
    git checkout ${INPUT_COMMIT_HASH}  # Using the input commit hash
    
    # Install Go dependencies
    go mod tidy
    
    # Build the 2MS binary
    go build -o /tmp/2ms main.go
    
    # Run the 2MS Scan
    /tmp/2ms
    
    # Run the entrypoint Python script
    python3 ./entrypoint.py
    "
