name: Run 2MS Scan

description: |
  GitHub Action that clones the repositories, builds the 2MS binary, installs dependencies, and runs the scan.

inputs:
  commit_hash:
    description: 'Commit hash to run the scan on'
    required: true

runs:
  using: "docker"
  image: "ubuntu:latest"
  entrypoint: "/bin/bash"
  args: |
    -c "
    sudo apt-get update
    sudo apt-get install -y python3 python3-pip git npm

    git clone --branch ${{ inputs.commit_hash }} https://github.com/checkmarx/2ms.git
    cd 2ms
    go mod tidy
    go build -o /tmp/2ms main.go
    /tmp/2ms
    python3 ./entrypoint.py
    "
