name: Run 2MS Scan

description: |
  GitHub Action that clones the repositories, runs 2ms scan, and merges the results.

inputs:
  repos:
    description: 'A JSON string of repositories to scan (with URLs)'
    required: true
    default: '[]'

runs:
  using: 'docker'
  image: 'ghcr.io/miguel-neiva01/2ms-github-action:latest'
  entrypoint: "python /entrypoint.py"
  env:
    REPOS_JSON: ${{ inputs.repos }}  #om os repositórios como uma variável de ambiente
