name: Run 2MS Scan

description: |
  GitHub Action que clona os repositórios, compila o 2MS, instala dependências e executa a análise.

inputs:
  commit_hash:
    description: 'Commit hash para executar o scan'
    required: true

runs:
  using: "docker"
  image: Dockerfile  # Usa o Dockerfile localmente
  env:
    INPUT_COMMIT_HASH: ${{ inputs.commit_hash }}
  args:
    - "--build-arg"
    - "COMMIT_HASH=${{ inputs.commit_hash }}"  # Passa o commit hash como argumento para o Dockerfile
