name: Run 2MS Scan

description: |
  GitHub Action that clones the repositories, builds the 2MS binary, installs dependencies, and runs the scan.

inputs:
  commit_hash:
    description: 'Commit hash to run the scan on'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout 2MS repository
      uses: actions/checkout@vb4ffde65f46336ab88eb53be808477a3936bae11
      with:
        repository: checkmarx/2ms
        ref: ${{ inputs.commit_hash }}  

    - name: Set up Go environment
      uses: actions/setup-go@v5
      with:
        go-version: "^1.22"  
    - name: Go mod tidy
      run: |
        go mod tidy
        git diff --exit-code

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip git npm
        npm install

    - name: Build 2MS binary
      run: |
        cd 2ms
        go build -o /tmp/2ms main.go

    - name: Run 2MS Scan
      run: |
        /tmp/2ms

    - name: Run entrypoint
      run: |
        python3 ./entrypoint.py
