name: Run 2MS Scan

description: |
  GitHub Action that clones the repositories, runs 2ms scan, and merges the results.

inputs:
  repos:
    description: 'A JSON string of repositories to scan (with URLs)'
    required: true
    default: '[]'

runs:
   using: "docker"
   image: Dockerfile

   env:
    REPOS_JSON: ${{ inputs.repos }} 
    RESULTS_DIR: /app/results

    RESULTS_DIR: /app/results

   args:
     - "/app/results/results.json"