name: '2ms Open Source Scan'
on:
  workflow_dispatch:

jobs:
  twoms-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone Repos
        run: |
          mkdir -p repos
          for repo in $(jq -r '.projects[]' repos.json); do
            target="repos/$(basename "$repo" .git)"
            echo "Cloning $repo into $target"
            git clone --depth=1 "$repo" "$target"
          done

      - name: Run 2ms Scan
        run: |
          mkdir -p results
          for repo_dir in repos/*; do 
            echo "Running 2ms for $repo_dir"
            docker run -v "$(pwd):/repos" -v "$(pwd)/results:/results" checkmarx/2ms:latest filesystem --path "/repos/$repo_dir" --ignore-on-exit results --report-path "/results/$(basename "$repo_dir").json"
          done

      - name: Get Json Results
        uses: actions/upload-artifact@v4
        with:
          name: json-results
          path: results/
