name: '2ms Open Source Scan'
on:
  workflow_dispatch:

jobs:
  twoms-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone Repos
        run: |
          mkdir -p repos
          for repo in $(jq -r '.projects[]' repos.json); do
            target="repos/$(basename "$repo" .git)"
            echo "Cloning $repo into $target"
            git clone --depth=1 "$repo" "$target"
          done
          
      - name: Set git safe directory
        run: git config --global --add safe.directory '*'
           
      - name: Verify git config
        run: git config --global --list

      - name: Run 2ms Scan
        run: |
          ls repos
          mkdir -p results
          for repo_dir in repos/*; do 
            echo "Running 2ms for $repo_dir"
            git config --global --add safe.directory /repos/gitleaks
            docker run --rm -v "$(pwd)/repos:/repos" checkmarx/2ms:latest sh -c "git config --global --add safe.directory /repos/$(basename "$repo_dir") && git /repos/$(basename "$repo_dir")"
          done

      - name: Upload SARIF's results
        uses: actions/upload-artifact@v4
        with:
          name: sarif-results
          path: results/
