name: Run 2ms Scan

on:
  push:
    branches:
      - main  

jobs:
  twoms-scan:
    runs-on: ubuntu-latest  

    steps:
      - name: Check out repository
        uses: actions/checkout@v3 
      - name: Run 2ms 
        uses: miguel-neiva01/2ms-github-action@v2.0.36
        with:
          commit_hash: fa250e1634b06a05444d40bdfe5235b19be09b54

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: 2ms-results
          path: results/  
          