name: Run 2ms Scan

on:
  push:
    branches:
      - main  

jobs:
  run-2ms-scan:
    runs-on: ubuntu-latest  

    steps:
      - name: Check out repository
        uses: actions/checkout@v3 

      - name: Run 2ms scan using 2ms GitHub Action
        uses: miguel-neiva01/2ms-github-action@v1.1.2

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: scan-results
          path: results/  